### ISSUE TITLE
Let's organize a demo party in Greece!

### ISSUE THREAD

**Issue by skmp** [dfnc/demoscenedotgr#1]
How about that? We were just discussing it with a friend. Maybe I can get NV to back some gifts or something. 

https://en.wikipedia.org/wiki/Demoscene#Parties << For those new to the demo scene

Also, http://demoscene.gr/about.php ~

**Comment by tenebrastudios** [comment]
We are totally behind that idea, both as professors in the field of Games Development and as Tenebra Studios! We will surely help in any capacity we can!

**Comment by luserx0** [comment]
Same goes here

**Comment by amycontiero** [comment]
Any idea about the date? What month would you guys recommend to organize this?

**Comment by skmp** [comment]
How about FEB? When are uni exams and such over?

**Comment by PanosJee** [comment]
Happy to help and host a demo at the Marathon VC office near the Acropolis (plenty of space for 30 ppl + projector)

**Comment by smessinis** [comment]
Let's do it. Count us in.

**Comment by bor0** [comment]
👍

**Comment by nyo16** [comment]
I will be @greece from mid Aug to mid September, i would love to join :)

**Comment by skmp** [comment]
@dfnc ?

**Comment by GusAndrianos** [comment]
I'm in!

**Comment by NoReasonException** [comment]
Im in!!! ^^

**Comment by ntemposd** [comment]
Nice initiative! If you r looking for space in Thess, [OK!Thess](https://okthess.gr/) could be the one.

**Comment by skmp** [comment]
@ntemposd I'm closer to Athens, but we could do two synchronized events, if there are enough people. Just like GGJ/HGJ. Also Patra could be interesting.

**Comment by plekkas** [comment]
Great idea!

**Comment by dfnc** [comment]
@skmp Well, this caught me a little off guard... Still,  I don't see how this is an issue of the demoscene.gr source code though. :P Anyway, it is not a bad idea, but if you are going to organize a mini-scale demoparty you will need a fixed location, say a place that can host 30+ people, a fixed due date say from 01 to 03 of a given month, sponsors to back up the event, and of course people that would help organizing it. As for me, I'm willing to participate if it happens but don't think I have the motivation to be in the organizing team. :P

**Comment by VelocityRa** [comment]
Yeah, and of course we'd need at least a few demogroups to present new demos.

Unless we allow already presented demos, is that a thing?

**Comment by dfnc** [comment]
> Yeah, and of course we'd need at least a few demogroups to present new demos.
> 
> Unless we allow already presented demos, is that a thing?

Well, most (if not all) demoparties do not allow submissions that have already entered other competitions.

You can accept remote entries though (a remote entry is a prod that the creator submits to a compo without being present at the demoparty).

**Comment by jtsiomb** [comment]
Absolutely. Announce the date early to give us time to make demos, and I'll certainly be there :)

-- Nuclear / The Lab & Mindlapse

**Comment by nikitasfrs** [comment]
Great initiative! I am interested :-)

**Comment by jtsiomb** [comment]
A couple of points about the realities of organizing a demoparty, since I see a lot of new people in this thread.

First of all, for people suggesting co-working spaces, or their offices as a partyplace, I just want to remind everyone that a demoparty is a non-stop 3-day event, with lots of people usually sleeping right there on chairs, tables, or under tables, which might or might not be appropriate for any particular space, but which must be kept in mind while selecting one.

There must be a certain degree of artifical darkness in the partyplace all day long (heavy curtains for instance) to maintain the ambiance, and keep the projector usable.

The electrical installation should be robust enough to allow the participants computers to draw current continuously without tripping the breakers or melting the distribution cables with a bang.

Also toilets must be cleaned routinely during the 3-days of the party (ideally).

The gardening/react/pixelshow partyplace at the university of patras was really a great place for most of these (apart for the toilet thing maybe), so it should not be overlooked as an option, if there is someone with connections to the university who can help organize that.

**Comment by skmp** [comment]
@jtsiomb I've been to several events organized at the cube, like the game jams, and all of those points were covered pretty well. Same goes for many other co-working spaces. My experiences with uni administrations and the education system have been extremely poisonous and demoralizing, so I'd rather stay away from any <<guardians of knowledge>> personally :)

I was chatting with @luserx0 and @VelocityRa and we'll meetup Tuesday around 19:00 at [hsgr](https://www.hackerspace.gr/wiki/Hackday). Anyone else interesting in showing up to have a <<pre-discussion>> about this?

~ cheers

**Comment by tenebrastudios** [comment]
Awesome idea skmp, let's get this party going! I have some ideas/proposals to bring on the table.

**Comment by jtsiomb** [comment]
I can't come to hsgr since I live in thessaloniki. But if you want to discuss this properly, I suggest all interested parties to join the grdemoscene mailing list, and for real-time chat, the #demo-gr IRC channel on grnet.

**Comment by skmp** [comment]
Taking notes https://pad.hackerspace.gr/p/demoparty. Joined on the channel on grnet, but looks kinda dead? Also joined the mailing list.

**Comment by jtsiomb** [comment]
Of course it's dead. There hasn't been an organized greek demoscene event in 11 years. But if people are interested, it's a good place to meet and talk about any new attempts to revitalize this thing. The mailing list is equally dead, but even more people who used to be in the greek demoscene are still subscribed there, even if they haven't posted in years. And it's a much better place to host such discussions than a random issue tracker on github :)

**Comment by dfnc** [comment]
It is evident from this discussion that what the greek demoscene community lacks is a proper modern day forum to discuss stuff like this. So after consideration I decided to create a group for the greek demoscene on steam: https://steamcommunity.com/groups/grdemoscene so if you have a steam account join the group where we can discuss about demos, demoparties, meet ups or anything else. :)

**Comment by jtsiomb** [comment]
Steam !? that's your take on a "modern day demoscene forum" ? :)
I prefer the mailing list, thanks ...

**Comment by skmp** [comment]
Sadly, it I won't be able to push/help for the organization of this. Would be great to see it happen, if someone else has the energy.
